### ISSUE TITLE
Previous images are there when using in modal

### ISSUE THREAD

**Issue by rafi73** [lekhang2512/vue-upload-multiple-image#1]
Hi, Thanks for the great plugin. I'm in middle of a situation. I'm using a Modal for uploading Images. When I open the modal for the first time it's working fine. After reopening the modal, I still can see the previous images are already there. I want to clear previous data / reset the plugin when I'm opening the modal everytime but can't. I've checked the events and right now little confused to manage the situation. I'm I missing something?

Thanks again.

**Comment by lekhang2512** [comment]
Bạn có thể thử v-if="images" đặt this.images = [ ] khi mở modal
