### ISSUE TITLE
How to edit primaryText to image name?

### ISSUE THREAD

**Issue by gret1111** [lekhang2512/vue-upload-multiple-image#11]
How to edit primaryText and markIsPrimaryText to each image name
I know that to set it is 
`primaryText="text"`
but I dont know how to set it to image name
Thanks!

**Comment by vishwapriyanatha** [comment]
<file-uploader
                        :maxImage="10"
                        :dragText="'Drag file or Click here to Upload'"
                        :browseText="'(Allowed File Types: jpg, png, gif)'"
                        :primaryText="'Default'"
                        :markIsPrimaryText="'Set as default'"
                        :popupText="'This image will be displayed as default'"
                        @upload-success="uploadImageSuccess"
                        @before-remove="beforeRemove"
                        @edit-image="editImage"
                        @data-change="dataChange"
                        :data-images="images"/>

**Comment by lekhang2512** [comment]
> How to edit primaryText and markIsPrimaryText to each image name
> I know that to set it is
> `primaryText="text"`
> but I dont know how to set it to image name
> Thanks!

You can use 
:primaryText="'value'"
:markIsPrimaryText="'value'"
