### ISSUE TITLE
How to pass existing images as props?

### ISSUE THREAD

**Issue by Xeragus** [lekhang2512/vue-upload-multiple-image#12]
I have images in database that I want to show in the component. They are stored as relative urls, ex: uploads/example.jpeg. Is it possible to pass the images to the component as props?

**Comment by uriwald** [comment]
Maybe not the best practice but in my case I  created a js variable ( json ) and then ..
`images: imagesJson,`

**Comment by lekhang2512** [comment]
> I have images in database that I want to show in the component. They are stored as relative urls, ex: uploads/example.jpeg. Is it possible to pass the images to the component as props?

You can use :data-images="images"
```
`images` has the structure:
```javascript
[
  {
    path: 'http://example.com/image.jpg',
    default: 1,
    highlight: 1,
    caption: 'caption to display. receive', // Optional
  }
]
```
