### ISSUE TITLE
Bug: Component allows Drag & Drop for files other than images the first time.

### ISSUE THREAD

**Issue by arellano-gustavo** [lekhang2512/vue-upload-multiple-image#13]
Way to reproduce the wrong behavior: Having the component in its initial state, with no images loaded, it is possible to drag (by example) a pdf file and, such a file is taken, showing in its place a small icon.

Additionally, I'd like to know if it is possible to detect the file's MIME in advance, so nobody can be able to upload a non image (yet renamed as a image) file.

**Comment by lekhang2512** [comment]
> Way to reproduce the wrong behavior: Having the component in its initial state, with no images loaded, it is possible to drag (by example) a pdf file and, such a file is taken, showing in its place a small icon.
> 
> Additionally, I'd like to know if it is possible to detect the file's MIME in advance, so nobody can be able to upload a non image (yet renamed as a image) file.

I fixed it and pushed git
