### ISSUE TITLE
Having more than one vue-upload-multiple-image problem

### ISSUE THREAD

**Issue by JFGHT** [lekhang2512/vue-upload-multiple-image#2]
If you do have two or more `vue-upload-multiple-image` in the same page, they won't work properly.

**Comment by lekhang2512** [comment]
Hi, I have fixed the error of displaying multiple components on the page and you can see the instructions in Readme.md

**Comment by izshreyansh** [comment]
@lekhang2512 Hey there.
Thank you so much for this plugin.

But i can't see instruciton on how to have multiple components on single page.
And i doesn't seem to work. Here's a [code sandbox link](https://codesandbox.io/s/vue-upload-multiple-imageissues2-vfy78).

> @JFGHT Hi, I have fixed the error of displaying multiple components on the page and you can see the instructions in Readme.md

Issue is: If you feed image to the second component, It will show up in the first one.

**Comment by izshreyansh** [comment]
Just going to put that here for a quick reference. Because i missed that from `README.MD`
You just have to pass a dynamic ID to these props
```
<vue-upload-multiple-image
    @upload-success="uploadImageSuccess"
    idUpload="uniqueId"
    editUpload="uniqueId">
</vue-upload-multiple-image>
```

**Comment by jonjieviduya** [comment]
@lekhang2512 What if the form is dynamic? Like when you click a button, it will generate a new item together with the idUpload. I tried it using `:id="index` but did not work. Any idea to make it dynamic?
