### ISSUE TITLE
Is it possible to modify the size of the component?

### ISSUE THREAD

**Issue by LancelotGHX** [lekhang2512/vue-upload-multiple-image#21]
Currently it is too small

**Comment by jbaroudi** [comment]
Hope this helps, in mounted lifecycle of Vue (use width and height you want):

	mounted() {
		// fix the image container
		var elems = document.querySelectorAll('.image-container')
		var index = 0
		var length = elems.length
		for (; index < length; index++) {
			(elems[index] as any).style.width = "500px";
			(elems[index] as any).style.height = "350px";
		}
		// fix the image preview of image loaded
		var prev = document.getElementById('.preview-image')
		if (prev !== null) {
			prev.style.height = "350px";
		}
	}

Setting a div wrapping the component like this with the class upload-container

	<div class="upload-container">
		<vue-upload-multiple-image :data-images="images" :maxImage="maxImages"></vue-upload-multiple-image>
	...

css like the example of vue-upload-multiple-image only added width and display

	.upload-container {
		font-family: 'Avenir', Helvetica, Arial, sans-serif;
		-webkit-font-smoothing: antialiased;
		-moz-osx-font-smoothing: grayscale;
		text-align: center;
		color: #2c3e50;
		display: flex;
		margin-top: 2.5em;
		width: 600px;
	}

**Comment by LancelotGHX** [comment]
Thanks a lot for the reply!
Very nice explanation!
