### ISSUE TITLE
How to hide the action button ?

### ISSUE THREAD

**Issue by muhammadbima20** [lekhang2512/vue-upload-multiple-image#24]
hi there, i had an issue in this package about how to hiding the action button (delete and edit)
so guys please tell me how to do it correctly.

any help will be very appreciated.

thanks

**Comment by lekhang2512** [comment]
> hi there, i had an issue in this package about how to hiding the action button (delete and edit)
> so guys please tell me how to do it correctly.
> 
> any help will be very appreciated.
> 
> thanks

You can use
