### ISSUE TITLE
Disable Multiple selection when browsing file

### ISSUE THREAD

**Issue by UrvashiGoswami** [lekhang2512/vue-upload-multiple-image#29]
How to disable multiple selection when browsing files?
This plugin is provide one prop **multiple** which is preventing multiple files. But i need multiple files with single selection in file browser. Any solution?  
User can select only one file with **ctrl** button

**Comment by lekhang2512** [comment]
> How to disable multiple selection when browsing files?
> This plugin is provide one prop **multiple** which is preventing multiple files. But i need multiple files with single selection in file browser. Any solution?
> User can select only one file with **ctrl** button

You can you props:  multiple=false
