### ISSUE TITLE
Possible to override 'width' and 'height' for div container?

### ISSUE THREAD

**Issue by asbjorn** [lekhang2512/vue-upload-multiple-image#5]
Hi.

The Vue component holds a scoped CSS stylesheet which doesn't easily allow to change the hardcoded 190px width of the parent container. I'm trying to embed this Vue component into in a webapp that needs to be mobile friendly. 

Would it be possible to keep the CSS "open" or somehow allow the *widht* and *height* to be overwritten?

**Comment by lekhang2512** [comment]
Currently I do not have time to upgrade this application yet. You can add class to <vue-upload-multiple-image: class = "custom"> and override the width height attribute
