### ISSUE TITLE
Cannot drag'n'drop several times

### ISSUE THREAD

**Issue by johnkristijan** [lekhang2512/vue-upload-multiple-image#8]
Steps to reproduce this error:
* Drag'n'drop or upload image(s)
* After the Vue component has been populated with 1 or more images, it's not possible to _drag'n'drop_ additional images into the vue component. There seem to be no drop-field available.
I can however add additional images by clicking the + button.

Anyone else experiencing this?

I'm using Google Chrome (Versjon 74.0.3729.108 (Offisiell delversjon) (64-bit))

![image](https://user-images.githubusercontent.com/33238136/56731918-fd3f9c00-675b-11e9-8152-f92acb7e2be9.png)

**Comment by AlimovTILLO** [comment]
How could you edit primaryText?

**Comment by arellano-gustavo** [comment]
I have the same behavior using Firefox: No more drag & drop after the first one...

**Comment by lekhang2512** [comment]
> How could you edit primaryText?

You can use props: primaryText this to change it

**Comment by lekhang2512** [comment]
> Steps to reproduce this error:
> 
> * Drag'n'drop or upload image(s)
> * After the Vue component has been populated with 1 or more images, it's not possible to _drag'n'drop_ additional images into the vue component. There seem to be no drop-field available.
>   I can however add additional images by clicking the + button.
> 
> Anyone else experiencing this?
> 
> I'm using Google Chrome (Versjon 74.0.3729.108 (Offisiell delversjon) (64-bit))
> 
> ![image](https://user-images.githubusercontent.com/33238136/56731918-fd3f9c00-675b-11e9-8152-f92acb7e2be9.png)

I fixed it and pushed it to git. Sorry for not being able to fix it sooner
