### ISSUE TITLE
How to edit dragText?

### ISSUE THREAD

**Issue by AlimovTILLO** [lekhang2512/vue-upload-multiple-image#9]
How i can replace dragText to another text?

**Comment by johnkristijan** [comment]
You can send in another variable or string into the property of the vue component:
      <vue-upload-multiple-image
        @upload-success="uploadImageSuccess"
        @before-remove="beforeRemove"
        @edit-image="editImage"
        @data-change="dataChange"
        :data-images="images"
        idUpload="myIdUpload"
        editUpload="myIdEdit"
        **:dragText="dragText"**
        dropText="DROP"
        :multiple="true"
        :browseText="browseText"
        :primaryText="primaryText"
        :markIsPrimaryText="markIsPrimaryText"
        :popupText="popupText"
        ></vue-upload-multiple-image>

**Comment by AlimovTILLO** [comment]
Thank you!
